### ISSUE TITLE
[Documentation] Citing this Action

### ISSUE THREAD

**Issue by kevinmatthes** [fregante/setup-git-user#12]
First of all, thank you for this Action!

I created various GitHub Actions myself making use of this one.  I would like add this Action to the respective lists of references for documentation.  Therefore, I would like to ask you how you intend this GitHub Action to be cited.  The target format is [CFF](https://github.com/citation-file-format/citation-file-format), but a BibTeX database entry or a plain text list of metadata would suffice, as well.

**Comment by fregante** [comment]
I'm not familiar with citations, so feel free to write it as you please. All the information is probably already in this repo. If you need anything let me know

**Comment by kevinmatthes** [comment]
Would you like to have the citation metadata for your repository?  GitHub uses the CFF standard to render a "Cite this repository" blob on the project's landing page such that people can copy the information for their lists of references.  This only requires the provision of a plain text configuration file named CITATION.cff.  If you are interested, I can set it up for you.

**Comment by fregante** [comment]
Not needed, thank you
