### ISSUE TITLE
v2.0.1 inside a container throws fatal: not in a git directory

### ISSUE THREAD

**Issue by AllanOricil** [fregante/setup-git-user#13]
Using v2.0.1
<img width="827" alt="image" src="https://user-images.githubusercontent.com/55927613/233074118-b53de7b7-014c-4b23-86bd-3ba9bb4ef1a3.png">

After changing to v1.1.0
<img width="1043" alt="image" src="https://user-images.githubusercontent.com/55927613/233074239-29b693a5-286f-4121-b14f-2f46a150fdd6.png">

Why cant we use v2.0.1 inside a container?

**Comment by fregante** [comment]
v1 just created a file in the file system. 

v2 uses git to set the config. 

If git says it's not a git folder, then you would have to debug the git command. Are you using actions/checkout before this action? It's impossible to debug without knowing what comes before.

**Comment by AllanOricil** [comment]
@fregante yes, there is a checkout action right before your action. I omitted it because the jobs are the same, the only difference beeing the version of your action. 
I also noticed that this issue started to happen only after I started running the job inside a docker container.
