### ISSUE TITLE
Fails if `~/.git/config` doesn't exist

### ISSUE THREAD

**Issue by mxcl** [fregante/setup-git-user#9]
On empty runners this file doesn’t exist

https://github.com/teaxyz/pantry.extra/actions/runs/4283515097/jobs/7459208690#step:6:12

**Comment by fregante** [comment]
Thank you for opening an issue. That's strange because it worked for me. I wonder if they changed something in recent versions of actions/checkout. Can you try with actions/checkout@v2?

**Comment by mxcl** [comment]
I would, but I can’t. There's waaaay too much machinery built on these actions.

All the same, seems like adding the flag to the appendFile call so it creates the file if it's non existent is a robustness choice.

Edit: when I say “empty runners” I mean runners built on slim containers like `debian:buster-slim`

Edit: and they don’t come with `git`. The checkout action doesn't actually use git to checkout. We install git ourselves later in this case.

**Comment by fregante** [comment]
PR welcome to add that flag if it fixes it. The built file also needs to be updated for a swift release 

In a future version it's very likely I'll replace this with actual calls to git as also demoed in the readme

**Comment by fregante** [comment]
This should be fixed in v2. However it's possible it might not work if your env does not allow global changes. Let me know if it works for you

**Comment by mxcl** [comment]
Thank you! I would have PR’d as I checked the code and could see it was easy going. But I appreciate not having to! I use this action in several projects. IMO it's how actions should be: tight and focused.
